name: github-actions-test
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.7'
      - uses: iterative/setup-cml@v1
      - name: Prepare data
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python get_data.py
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python train.py
          cat results.txt >> report.md
          cml-publish lin_reg_visualisation.png --md >> report.md
          cml-send-comment report.md